#!/usr/bin/env python3
"""Generate complete 8D reports JSON data with detailed content"""

import json

reports = [
    {"id":1,"supplier":"巴马铂泉","product":"饮用水","issue":"标签脱落","score":40,"grade":"不合格","scores":{"D1":6,"D2":2,"D3":4,"D4":12,"D5":12,"D6":0,"D7":3,"D8":1},"highlights":["D4鱼骨图12个分析点，5WHY产生原因完成3层推演"],"shortcomings":["D6完全空白","D2联系方式大部分空白","D5无跟踪人/日期"],"details":{"D1":{"score":6,"max":10,"highlights":"5W1H有表格框架，有缺陷件照片","shortcomings":"无量化数据、无对客影响说明","original":"供应商提供了5W1H表格框架，包含时间、地点、发现人、问题、数量等基本信息，并附有缺陷件照片。","learning":"优秀案例应包含：批次总量、不良率、涉及门店数、对客影响量化说明。参考报告5（北京新青人）的D1，量化数据极其详细。"},"D2":{"score":2,"max":5,"highlights":"团队覆盖组长和组员","shortcomings":"电话邮箱大部分空白","original":"团队包含组长和组员，但联系方式填写不完整。","learning":"优秀案例应包含：5人团队满编、电话邮箱全部填写、各成员职责分工明确。参考报告5（北京新青人）的D2，电话邮箱全部填写。"},"D3":{"score":4,"max":10,"highlights":"有临时措施（隔离、排查）","shortcomings":"无断点日期、围堵作业表空白","original":"供应商采取了隔离疑似问题批次、库存全检等临时措施。","learning":"优秀案例应包含：遏制断点日期、客户端断点日期、围堵作业表完整数据（客户端/经销商/运输/仓库各环节排查数据）。参考报告44（金可儿）的D3。"},"D4":{"score":12,"max":25,"highlights":"鱼骨图12个分析点，5WHY产生原因完成3层","shortcomings":"流出原因/系统原因5WHY仅1层","original":"供应商提供了鱼骨图（12个分析点），5WHY产生原因完成3层推演。","learning":"优秀案例应包含：鱼骨图13+分析点、5WHY三个方面（产生/流出/系统）全部完成5层推演、根因定位到管理层面。参考报告5（北京新青人）的D4。"},"D5":{"score":12,"max":20,"highlights":"按防产生/防流出/系统改善分类","shortcomings":"无跟踪人/完成日期、措施空泛","original":"措施按防产生/防流出/系统改善分类，但缺乏具体执行细节。","learning":"优秀案例应包含：跟踪人、完成日期、量化标准、具体措施（避免'加强培训'等空泛表述）。参考报告44（金可儿）的D5。"},"D6":{"score":0,"max":15,"highlights":"无","shortcomings":"完全空白","original":"无改善措施验证内容。","learning":"优秀案例应包含：改善前数据、改善后数据、验证方法、验证结论、门店端使用验证。参考报告85（四川环龙）的D6，有三阶段验证数据。"},"D7":{"score":3,"max":10,"highlights":"文件更新清单有2项标记'是'","shortcomings":"无完成日期、无横向排查","original":"文件更新清单有2项标记'是'，但缺乏完成日期和证据。","learning":"优秀案例应包含：文件更新清单完整（9+项）、完成日期、证据描述、横向排查。参考报告5（北京新青人）的D7，文件更新9项。"},"D8":{"score":1,"max":5,"highlights":"有横向展开表","shortcomings":"仅1行、无知识共享","original":"有横向展开表，但仅1行内容。","learning":"优秀案例应包含：横向展开6+项目、知识共享、团队表彰。参考报告6（北京新青人）的D8，横向展开6个项目。"}}},
    {"id":2,"supplier":"巴马铂泉","product":"饮用水","issue":"液位不统一","score":44,"grade":"不合格","scores":{"D1":5,"D2":2,"D3":4,"D4":10,"D5":14,"D6":5,"D7":3,"D8":1},"highlights":["D4鱼骨图10个分析点，5WHY产生原因完成3层推演"],"shortcomings":["D2联系方式大部分空白","D5无跟踪人/日期","D6无量化数据"],"details":{"D1":{"score":5,"max":10,"highlights":"5W1H有表格框架","shortcomings":"无量化数据、无照片","original":"供应商提供了5W1H表格框架，包含基本信息。","learning":"优秀案例应包含：缺陷件照片、批次总量、不良率、对客影响量化。参考报告5（北京新青人）的D1。"},"D2":{"score":2,"max":5,"highlights":"团队覆盖组长和组员","shortcomings":"电话邮箱大部分空白","original":"团队包含组长和组员，但联系方式填写不完整。","learning":"优秀案例应包含：5人团队满编、电话邮箱全部填写。参考报告5（北京新青人）的D2。"},"D3":{"score":4,"max":10,"highlights":"有临时措施","shortcomings":"无断点日期、围堵作业表空白","original":"供应商采取了临时措施，但缺乏断点日期和围堵数据。","learning":"优秀案例应包含：断点日期、围堵作业表完整数据。参考报告44（金可儿）的D3。"},"D4":{"score":10,"max":25,"highlights":"鱼骨图10个分析点，5WHY产生原因完成3层","shortcomings":"流出原因/系统原因5WHY仅1层","original":"供应商提供了鱼骨图（10个分析点），5WHY产生原因完成3层推演。","learning":"优秀案例应包含：5WHY三个方面全部完成5层推演。参考报告5（北京新青人）的D4。"},"D5":{"score":14,"max":20,"highlights":"按防产生/防流出/系统改善分类","shortcomings":"无跟踪人/完成日期","original":"措施按防产生/防流出/系统改善分类，但缺乏执行细节。","learning":"优秀案例应包含：跟踪人、完成日期、量化标准。参考报告44（金可儿）的D5。"},"D6":{"score":5,"max":15,"highlights":"有验证描述","shortcomings":"无量化数据、无照片","original":"有验证描述，但缺乏量化数据和照片。","learning":"优秀案例应包含：改善前/改善后数据对比、验证照片。参考报告85（四川环龙）的D6。"},"D7":{"score":3,"max":10,"highlights":"文件更新清单有2项标记'是'","shortcomings":"无完成日期、无横向排查","original":"文件更新清单有2项标记'是'，但缺乏完成日期。","learning":"优秀案例应包含：文件更新清单完整、完成日期、横向排查。参考报告5（北京新青人）的D7。"},"D8":{"score":1,"max":5,"highlights":"有横向展开表","shortcomings":"仅1行、无知识共享","original":"有横向展开表，但仅1行内容。","learning":"优秀案例应包含：横向展开6+项目、知识共享。参考报告6（北京新青人）的D8。"}}},
    {"id":3,"supplier":"朵爱","product":"洗沐","issue":"按头按压不出","score":70,"grade":"合格","scores":{"D1":8,"D2":4,"D3":7,"D4":22,"D5":18,"D6":0,"D7":7,"D8":4},"highlights":["D4 5WHY三个方面全部完成5层推演","D2团队满分"],"shortcomings":["D6完全空白","D7无横向排查"],"details":{"D1":{"score":8,"max":10,"highlights":"5W1H完整、有量化数据、有照片","shortcomings":"无对客影响说明","original":"供应商提供了完整的5W1H表格，包含量化数据和缺陷件照片。","learning":"优秀案例应包含：对客影响量化说明。参考报告5（北京新青人）的D1。"},"D2":{"score":4,"max":5,"highlights":"5人团队满编、电话邮箱全部填写","shortcomings":"缺职责分工","original":"5人团队满编，电话邮箱全部填写。","learning":"优秀案例应包含：各成员职责分工明确。参考报告5（北京新青人）的D2。"},"D3":{"score":7,"max":10,"highlights":"有断点日期、围堵数据完整","shortcomings":"无照片","original":"有断点日期和围堵数据，但缺乏照片。","learning":"优秀案例应包含：临时措施照片、产品断点标识照片。参考报告44（金可儿）的D3。"},"D4":{"score":22,"max":25,"highlights":"鱼骨图13个分析点、5WHY三个方面全部完成5层推演","shortcomings":"系统原因第5层可再深挖","original":"鱼骨图13个分析点，5WHY三个方面全部完成5层推演。","learning":"优秀案例应包含：系统原因第5层深挖到管理/流程层面。参考报告5（北京新青人）的D4。"},"D5":{"score":18,"max":20,"highlights":"措施具体、有量化标准","shortcomings":"无验收标准","original":"措施具体，有量化标准，但缺乏验收标准。","learning":"优秀案例应包含：验收标准、文件编号与版本。参考报告44（金可儿）的D5。"},"D6":{"score":0,"max":15,"highlights":"无","shortcomings":"完全空白","original":"无改善措施验证内容。","learning":"优秀案例应包含：改善前/改善后数据对比、验证照片、门店端验证。参考报告85（四川环龙）的D6。"},"D7":{"score":7,"max":10,"highlights":"文件更新清单5项标记'是'","shortcomings":"无横向排查","original":"文件更新清单5项标记'是'，但缺乏横向排查。","learning":"优秀案例应包含：横向排查、横向标准化展开。参考报告5（北京新青人）的D7。"},"D8":{"score":4,"max":5,"highlights":"横向展开4个项目","shortcomings":"无知识共享","original":"横向展开4个项目，但缺乏知识共享。","learning":"优秀案例应包含：知识共享、团队表彰。参考报告6（北京新青人）的D8。"}}},
    {"id":4,"supplier":"创诚家居","product":"窗帘","issue":"滑车臂断裂","score":81,"grade":"良好","scores":{"D1":8,"D2":3,"D3":8,"D4":23,"D5":19,"D6":13,"D7":8,"D8":3},"highlights":["D4鱼骨图15+分析点，5WHY完整","D6有4种测试对比"],"shortcomings":["D2联系方式大部分空白","D7无横向排查"],"details":{"D1":{"score":8,"max":10,"highlights":"5W1H完整、有量化数据、有照片","shortcomings":"无对客影响说明","original":"5W1H完整，有量化数据和缺陷件照片。","learning":"优秀案例应包含：对客影响量化说明。参考报告5（北京新青人）的D1。"},"D2":{"score":3,"max":5,"highlights":"5人团队满编","shortcomings":"电话邮箱大部分空白","original":"5人团队满编，但联系方式填写不完整。","learning":"优秀案例应包含：电话邮箱全部填写。参考报告5（北京新青人）的D2。"},"D3":{"score":8,"max":10,"highlights":"有断点日期、围堵数据完整","shortcomings":"无照片","original":"有断点日期和围堵数据，但缺乏照片。","learning":"优秀案例应包含：临时措施照片。参考报告44（金可儿）的D3。"},"D4":{"score":23,"max":25,"highlights":"鱼骨图15+分析点、5WHY三个方面全部完成5层推演","shortcomings":"系统原因第5层可再深挖","original":"鱼骨图15+分析点，5WHY三个方面全部完成5层推演。","learning":"优秀案例应包含：系统原因第5层深挖到管理层面。参考报告5（北京新青人）的D4。"},"D5":{"score":19,"max":20,"highlights":"措施极其具体、有量化标准","shortcomings":"无验收标准","original":"措施极其具体，有量化标准，但缺乏验收标准。","learning":"优秀案例应包含：验收标准。参考报告44（金可儿）的D5。"},"D6":{"score":13,"max":15,"highlights":"有4种测试对比数据","shortcomings":"无门店端验证","original":"有4种测试对比数据，但缺乏门店端验证。","learning":"优秀案例应包含：门店端使用验证数据。参考报告85（四川环龙）的D6。"},"D7":{"score":8,"max":10,"highlights":"文件更新清单7项标记'是'","shortcomings":"无横向排查","original":"文件更新清单7项标记'是'，但缺乏横向排查。","learning":"优秀案例应包含：横向排查。参考报告5（北京新青人）的D7。"},"D8":{"score":3,"max":5,"highlights":"横向展开3个项目","shortcomings":"无知识共享","original":"横向展开3个项目，但缺乏知识共享。","learning":"优秀案例应包含：知识共享、团队表彰。参考报告6（北京新青人）的D8。"}}},
    {"id":5,"supplier":"北京新青人","product":"窗帘","issue":"塑料调节挂钩断裂","score":94,"grade":"优秀","scores":{"D1":9,"D2":5,"D3":9,"D4":24,"D5":19,"D6":14,"D7":10,"D8":4},"highlights":["D1满分、D2满分、D7满分","D4鱼骨图15+分析点，5WHY完整","D6验证数据极其详细"],"shortcomings":["几乎无明显短板，仅D3无照片、D5无验收标准"],"details":{"D1":{"score":9,"max":10,"highlights":"5W1H极其完整、量化数据极其详细、有照片","shortcomings":"无对客影响说明","original":"5W1H极其完整，量化数据极其详细（3,200条/1,450条/45.3%），有缺陷件和合格件对比照片。","learning":"这是标杆案例！量化数据极其详细，包含批次总量、不良率、涉及门店数。唯一不足是无对客影响说明。"},"D2":{"score":5,"max":5,"highlights":"6人团队满编、电话邮箱全部填写","shortcomings":"无","original":"6人团队满编，电话邮箱全部填写，专业覆盖合理。","learning":"这是标杆案例！团队满编，联系方式全部填写，是少数几份邮箱全满的报告。"},"D3":{"score":9,"max":10,"highlights":"有断点日期、围堵数据极其完整","shortcomings":"无照片","original":"有断点日期，围堵数据极其完整（每个环节都有排查数据）。","learning":"这是标杆案例！围堵数据极其完整，每个环节都有排查数据。唯一不足是无照片。"},"D4":{"score":24,"max":25,"highlights":"鱼骨图15+分析点、5WHY三个方面全部完成5层推演","shortcomings":"系统原因第5层可再深挖","original":"鱼骨图15+分析点，5WHY三个方面全部完成5层推演，逻辑链条极其完整。","learning":"这是标杆案例！5WHY三个方面全部完成5层推演，根因定位精准。"},"D5":{"score":19,"max":20,"highlights":"措施极其具体、有量化标准","shortcomings":"无验收标准","original":"措施极其具体，有量化标准（温度180℃/张力18N/m/进布速度8m/min）。","learning":"这是标杆案例！措施极其具体，有量化标准。唯一不足是无验收标准。"},"D6":{"score":14,"max":15,"highlights":"有极其详细的验证数据","shortcomings":"无门店端验证","original":"有极其详细的验证数据（改善前4.8% vs 改善后经向1.4%/纬向1.2%）。","learning":"这是标杆案例！验证数据极其详细，有改善前/改善后对比。唯一不足是无门店端验证。"},"D7":{"score":10,"max":10,"highlights":"文件更新清单9项标记'是'，证据极其详细","shortcomings":"无","original":"文件更新清单9项标记'是'，证据极其详细。","learning":"这是标杆案例！文件更新9项，证据极其详细，覆盖极广。"},"D8":{"score":4,"max":5,"highlights":"横向展开6个项目","shortcomings":"无团队表彰","original":"横向展开6个项目，覆盖全系列床品填芯产品。","learning":"这是标杆案例！横向展开6个项目，有'不适用'的专业判断。唯一不足是无团队表彰。"}}}
]

data = {
    "meta": {
        "title": "华住运营品类质量铁训营8D报告批改结果",
        "version": "V2.0",
        "total": 118,
        "updateDate": "2026-06-17"
    },
    "reports": reports
}

with open('data/reports.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Generated {len(reports)} reports with detailed content")